/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiErrorError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiErrorError{}

// ApiErrorError struct for ApiErrorError
type ApiErrorError struct {
	// A stable machine-readable error code.
	Code string `json:"code"`
	// A human-readable explanation.
	Message string `json:"message"`
}

type _ApiErrorError ApiErrorError

// NewApiErrorError instantiates a new ApiErrorError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiErrorError(code string, message string) *ApiErrorError {
	this := ApiErrorError{}
	this.Code = code
	this.Message = message
	return &this
}

// NewApiErrorErrorWithDefaults instantiates a new ApiErrorError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiErrorErrorWithDefaults() *ApiErrorError {
	this := ApiErrorError{}
	return &this
}

// GetCode returns the Code field value
func (o *ApiErrorError) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ApiErrorError) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ApiErrorError) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *ApiErrorError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ApiErrorError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ApiErrorError) SetMessage(v string) {
	o.Message = v
}

func (o ApiErrorError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiErrorError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ApiErrorError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiErrorError := _ApiErrorError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiErrorError)

	if err != nil {
		return err
	}

	*o = ApiErrorError(varApiErrorError)

	return err
}

type NullableApiErrorError struct {
	value *ApiErrorError
	isSet bool
}

func (v NullableApiErrorError) Get() *ApiErrorError {
	return v.value
}

func (v *NullableApiErrorError) Set(val *ApiErrorError) {
	v.value = val
	v.isSet = true
}

func (v NullableApiErrorError) IsSet() bool {
	return v.isSet
}

func (v *NullableApiErrorError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiErrorError(val *ApiErrorError) *NullableApiErrorError {
	return &NullableApiErrorError{value: val, isSet: true}
}

func (v NullableApiErrorError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiErrorError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


