/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccountStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountStatusResponse{}

// AccountStatusResponse struct for AccountStatusResponse
type AccountStatusResponse struct {
	Credits AccountStatusResponseCredits `json:"credits"`
	RateLimit AccountStatusResponseRateLimit `json:"rate_limit"`
	// The plan behind the key.
	Plan NullableString `json:"plan,omitempty"`
	// Whether the key is a sandbox key (es_test_).
	Sandbox bool `json:"sandbox"`
}

type _AccountStatusResponse AccountStatusResponse

// NewAccountStatusResponse instantiates a new AccountStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountStatusResponse(credits AccountStatusResponseCredits, rateLimit AccountStatusResponseRateLimit, sandbox bool) *AccountStatusResponse {
	this := AccountStatusResponse{}
	this.Credits = credits
	this.RateLimit = rateLimit
	this.Sandbox = sandbox
	return &this
}

// NewAccountStatusResponseWithDefaults instantiates a new AccountStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountStatusResponseWithDefaults() *AccountStatusResponse {
	this := AccountStatusResponse{}
	return &this
}

// GetCredits returns the Credits field value
func (o *AccountStatusResponse) GetCredits() AccountStatusResponseCredits {
	if o == nil {
		var ret AccountStatusResponseCredits
		return ret
	}

	return o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value
// and a boolean to check if the value has been set.
func (o *AccountStatusResponse) GetCreditsOk() (*AccountStatusResponseCredits, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credits, true
}

// SetCredits sets field value
func (o *AccountStatusResponse) SetCredits(v AccountStatusResponseCredits) {
	o.Credits = v
}

// GetRateLimit returns the RateLimit field value
func (o *AccountStatusResponse) GetRateLimit() AccountStatusResponseRateLimit {
	if o == nil {
		var ret AccountStatusResponseRateLimit
		return ret
	}

	return o.RateLimit
}

// GetRateLimitOk returns a tuple with the RateLimit field value
// and a boolean to check if the value has been set.
func (o *AccountStatusResponse) GetRateLimitOk() (*AccountStatusResponseRateLimit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RateLimit, true
}

// SetRateLimit sets field value
func (o *AccountStatusResponse) SetRateLimit(v AccountStatusResponseRateLimit) {
	o.RateLimit = v
}

// GetPlan returns the Plan field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccountStatusResponse) GetPlan() string {
	if o == nil || IsNil(o.Plan.Get()) {
		var ret string
		return ret
	}
	return *o.Plan.Get()
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccountStatusResponse) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Plan.Get(), o.Plan.IsSet()
}

// HasPlan returns a boolean if a field has been set.
func (o *AccountStatusResponse) HasPlan() bool {
	if o != nil && o.Plan.IsSet() {
		return true
	}

	return false
}

// SetPlan gets a reference to the given NullableString and assigns it to the Plan field.
func (o *AccountStatusResponse) SetPlan(v string) {
	o.Plan.Set(&v)
}
// SetPlanNil sets the value for Plan to be an explicit nil
func (o *AccountStatusResponse) SetPlanNil() {
	o.Plan.Set(nil)
}

// UnsetPlan ensures that no value is present for Plan, not even an explicit nil
func (o *AccountStatusResponse) UnsetPlan() {
	o.Plan.Unset()
}

// GetSandbox returns the Sandbox field value
func (o *AccountStatusResponse) GetSandbox() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value
// and a boolean to check if the value has been set.
func (o *AccountStatusResponse) GetSandboxOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sandbox, true
}

// SetSandbox sets field value
func (o *AccountStatusResponse) SetSandbox(v bool) {
	o.Sandbox = v
}

func (o AccountStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credits"] = o.Credits
	toSerialize["rate_limit"] = o.RateLimit
	if o.Plan.IsSet() {
		toSerialize["plan"] = o.Plan.Get()
	}
	toSerialize["sandbox"] = o.Sandbox
	return toSerialize, nil
}

func (o *AccountStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credits",
		"rate_limit",
		"sandbox",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountStatusResponse := _AccountStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountStatusResponse)

	if err != nil {
		return err
	}

	*o = AccountStatusResponse(varAccountStatusResponse)

	return err
}

type NullableAccountStatusResponse struct {
	value *AccountStatusResponse
	isSet bool
}

func (v NullableAccountStatusResponse) Get() *AccountStatusResponse {
	return v.value
}

func (v *NullableAccountStatusResponse) Set(val *AccountStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountStatusResponse(val *AccountStatusResponse) *NullableAccountStatusResponse {
	return &NullableAccountStatusResponse{value: val, isSet: true}
}

func (v NullableAccountStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


