/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyJobResponse{}

// VerifyJobResponse struct for VerifyJobResponse
type VerifyJobResponse struct {
	// The job id. Use it to poll GET /v1/verify/jobs/{id}.
	Id string `json:"id"`
	// Job state.
	Status string `json:"status"`
	// Number of submitted addresses.
	Total int32 `json:"total"`
	Progress VerifyJobResponseProgress `json:"progress"`
	// When the job was submitted (ISO 8601).
	CreatedAt string `json:"created_at"`
	// When the results are purged (ISO 8601, 7 days after submit).
	ExpiresAt string `json:"expires_at"`
	// One entry per submitted address, in order. Present only when status is completed. Entries are verify results, or per-item errors ({email, error}) for addresses that could not be processed.
	Results []map[string]interface{} `json:"results,omitempty"`
}

type _VerifyJobResponse VerifyJobResponse

// NewVerifyJobResponse instantiates a new VerifyJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyJobResponse(id string, status string, total int32, progress VerifyJobResponseProgress, createdAt string, expiresAt string) *VerifyJobResponse {
	this := VerifyJobResponse{}
	this.Id = id
	this.Status = status
	this.Total = total
	this.Progress = progress
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	return &this
}

// NewVerifyJobResponseWithDefaults instantiates a new VerifyJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyJobResponseWithDefaults() *VerifyJobResponse {
	this := VerifyJobResponse{}
	return &this
}

// GetId returns the Id field value
func (o *VerifyJobResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VerifyJobResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VerifyJobResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *VerifyJobResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *VerifyJobResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *VerifyJobResponse) SetStatus(v string) {
	o.Status = v
}

// GetTotal returns the Total field value
func (o *VerifyJobResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *VerifyJobResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *VerifyJobResponse) SetTotal(v int32) {
	o.Total = v
}

// GetProgress returns the Progress field value
func (o *VerifyJobResponse) GetProgress() VerifyJobResponseProgress {
	if o == nil {
		var ret VerifyJobResponseProgress
		return ret
	}

	return o.Progress
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
func (o *VerifyJobResponse) GetProgressOk() (*VerifyJobResponseProgress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progress, true
}

// SetProgress sets field value
func (o *VerifyJobResponse) SetProgress(v VerifyJobResponseProgress) {
	o.Progress = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *VerifyJobResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *VerifyJobResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *VerifyJobResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *VerifyJobResponse) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *VerifyJobResponse) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *VerifyJobResponse) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

// GetResults returns the Results field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyJobResponse) GetResults() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyJobResponse) GetResultsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *VerifyJobResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []map[string]interface{} and assigns it to the Results field.
func (o *VerifyJobResponse) SetResults(v []map[string]interface{}) {
	o.Results = v
}

func (o VerifyJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["total"] = o.Total
	toSerialize["progress"] = o.Progress
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["expires_at"] = o.ExpiresAt
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

func (o *VerifyJobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"total",
		"progress",
		"created_at",
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyJobResponse := _VerifyJobResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyJobResponse)

	if err != nil {
		return err
	}

	*o = VerifyJobResponse(varVerifyJobResponse)

	return err
}

type NullableVerifyJobResponse struct {
	value *VerifyJobResponse
	isSet bool
}

func (v NullableVerifyJobResponse) Get() *VerifyJobResponse {
	return v.value
}

func (v *NullableVerifyJobResponse) Set(val *VerifyJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyJobResponse(val *VerifyJobResponse) *NullableVerifyJobResponse {
	return &NullableVerifyJobResponse{value: val, isSet: true}
}

func (v NullableVerifyJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


