/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifySingleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifySingleRequest{}

// VerifySingleRequest struct for VerifySingleRequest
type VerifySingleRequest struct {
	// The address to verify.
	Email string `json:"email"`
}

type _VerifySingleRequest VerifySingleRequest

// NewVerifySingleRequest instantiates a new VerifySingleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifySingleRequest(email string) *VerifySingleRequest {
	this := VerifySingleRequest{}
	this.Email = email
	return &this
}

// NewVerifySingleRequestWithDefaults instantiates a new VerifySingleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifySingleRequestWithDefaults() *VerifySingleRequest {
	this := VerifySingleRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *VerifySingleRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *VerifySingleRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *VerifySingleRequest) SetEmail(v string) {
	o.Email = v
}

func (o VerifySingleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifySingleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *VerifySingleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifySingleRequest := _VerifySingleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifySingleRequest)

	if err != nil {
		return err
	}

	*o = VerifySingleRequest(varVerifySingleRequest)

	return err
}

type NullableVerifySingleRequest struct {
	value *VerifySingleRequest
	isSet bool
}

func (v NullableVerifySingleRequest) Get() *VerifySingleRequest {
	return v.value
}

func (v *NullableVerifySingleRequest) Set(val *VerifySingleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifySingleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifySingleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifySingleRequest(val *VerifySingleRequest) *NullableVerifySingleRequest {
	return &NullableVerifySingleRequest{value: val, isSet: true}
}

func (v NullableVerifySingleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifySingleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


