/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
)

// checks if the AccountStatusResponseCredits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountStatusResponseCredits{}

// AccountStatusResponseCredits Credit balance buckets.
type AccountStatusResponseCredits struct {
	// Spendable credits across all buckets.
	Total *int32 `json:"total,omitempty"`
	Purchased *int32 `json:"purchased,omitempty"`
	Gifted *int32 `json:"gifted,omitempty"`
}

// NewAccountStatusResponseCredits instantiates a new AccountStatusResponseCredits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountStatusResponseCredits() *AccountStatusResponseCredits {
	this := AccountStatusResponseCredits{}
	return &this
}

// NewAccountStatusResponseCreditsWithDefaults instantiates a new AccountStatusResponseCredits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountStatusResponseCreditsWithDefaults() *AccountStatusResponseCredits {
	this := AccountStatusResponseCredits{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AccountStatusResponseCredits) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountStatusResponseCredits) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AccountStatusResponseCredits) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *AccountStatusResponseCredits) SetTotal(v int32) {
	o.Total = &v
}

// GetPurchased returns the Purchased field value if set, zero value otherwise.
func (o *AccountStatusResponseCredits) GetPurchased() int32 {
	if o == nil || IsNil(o.Purchased) {
		var ret int32
		return ret
	}
	return *o.Purchased
}

// GetPurchasedOk returns a tuple with the Purchased field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountStatusResponseCredits) GetPurchasedOk() (*int32, bool) {
	if o == nil || IsNil(o.Purchased) {
		return nil, false
	}
	return o.Purchased, true
}

// HasPurchased returns a boolean if a field has been set.
func (o *AccountStatusResponseCredits) HasPurchased() bool {
	if o != nil && !IsNil(o.Purchased) {
		return true
	}

	return false
}

// SetPurchased gets a reference to the given int32 and assigns it to the Purchased field.
func (o *AccountStatusResponseCredits) SetPurchased(v int32) {
	o.Purchased = &v
}

// GetGifted returns the Gifted field value if set, zero value otherwise.
func (o *AccountStatusResponseCredits) GetGifted() int32 {
	if o == nil || IsNil(o.Gifted) {
		var ret int32
		return ret
	}
	return *o.Gifted
}

// GetGiftedOk returns a tuple with the Gifted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountStatusResponseCredits) GetGiftedOk() (*int32, bool) {
	if o == nil || IsNil(o.Gifted) {
		return nil, false
	}
	return o.Gifted, true
}

// HasGifted returns a boolean if a field has been set.
func (o *AccountStatusResponseCredits) HasGifted() bool {
	if o != nil && !IsNil(o.Gifted) {
		return true
	}

	return false
}

// SetGifted gets a reference to the given int32 and assigns it to the Gifted field.
func (o *AccountStatusResponseCredits) SetGifted(v int32) {
	o.Gifted = &v
}

func (o AccountStatusResponseCredits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountStatusResponseCredits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Purchased) {
		toSerialize["purchased"] = o.Purchased
	}
	if !IsNil(o.Gifted) {
		toSerialize["gifted"] = o.Gifted
	}
	return toSerialize, nil
}

type NullableAccountStatusResponseCredits struct {
	value *AccountStatusResponseCredits
	isSet bool
}

func (v NullableAccountStatusResponseCredits) Get() *AccountStatusResponseCredits {
	return v.value
}

func (v *NullableAccountStatusResponseCredits) Set(val *AccountStatusResponseCredits) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountStatusResponseCredits) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountStatusResponseCredits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountStatusResponseCredits(val *AccountStatusResponseCredits) *NullableAccountStatusResponseCredits {
	return &NullableAccountStatusResponseCredits{value: val, isSet: true}
}

func (v NullableAccountStatusResponseCredits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountStatusResponseCredits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


