/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GuardEventsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuardEventsRequest{}

// GuardEventsRequest struct for GuardEventsRequest
type GuardEventsRequest struct {
	// Guard decision events to record. Non-empty, capped per the batch limit. Each item: {domain?, verdict, action, reasons[], degraded, source, integration?, lib_version?, spec_version?, property_key?}. The full email address is never sent, only the domain. property_key is the optional public site-key of a property (EM-998); when it matches one of your properties the event is attributed to it, otherwise the event still records at the account level.
	Events []map[string]interface{} `json:"events"`
}

type _GuardEventsRequest GuardEventsRequest

// NewGuardEventsRequest instantiates a new GuardEventsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuardEventsRequest(events []map[string]interface{}) *GuardEventsRequest {
	this := GuardEventsRequest{}
	this.Events = events
	return &this
}

// NewGuardEventsRequestWithDefaults instantiates a new GuardEventsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuardEventsRequestWithDefaults() *GuardEventsRequest {
	this := GuardEventsRequest{}
	return &this
}

// GetEvents returns the Events field value
func (o *GuardEventsRequest) GetEvents() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *GuardEventsRequest) GetEventsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *GuardEventsRequest) SetEvents(v []map[string]interface{}) {
	o.Events = v
}

func (o GuardEventsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuardEventsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *GuardEventsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGuardEventsRequest := _GuardEventsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGuardEventsRequest)

	if err != nil {
		return err
	}

	*o = GuardEventsRequest(varGuardEventsRequest)

	return err
}

type NullableGuardEventsRequest struct {
	value *GuardEventsRequest
	isSet bool
}

func (v NullableGuardEventsRequest) Get() *GuardEventsRequest {
	return v.value
}

func (v *NullableGuardEventsRequest) Set(val *GuardEventsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGuardEventsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGuardEventsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuardEventsRequest(val *GuardEventsRequest) *NullableGuardEventsRequest {
	return &NullableGuardEventsRequest{value: val, isSet: true}
}

func (v NullableGuardEventsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuardEventsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


