/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
)

// checks if the AccountStatusResponseRateLimit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountStatusResponseRateLimit{}

// AccountStatusResponseRateLimit The per-key sliding-window rate limit.
type AccountStatusResponseRateLimit struct {
	// Requests per minute for this key.
	Limit *int32 `json:"limit,omitempty"`
	// Requests left in the current window. This call counted against it.
	Remaining *int32 `json:"remaining,omitempty"`
	// Unix timestamp when the window frees up.
	Reset *int32 `json:"reset,omitempty"`
}

// NewAccountStatusResponseRateLimit instantiates a new AccountStatusResponseRateLimit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountStatusResponseRateLimit() *AccountStatusResponseRateLimit {
	this := AccountStatusResponseRateLimit{}
	return &this
}

// NewAccountStatusResponseRateLimitWithDefaults instantiates a new AccountStatusResponseRateLimit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountStatusResponseRateLimitWithDefaults() *AccountStatusResponseRateLimit {
	this := AccountStatusResponseRateLimit{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *AccountStatusResponseRateLimit) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountStatusResponseRateLimit) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *AccountStatusResponseRateLimit) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *AccountStatusResponseRateLimit) SetLimit(v int32) {
	o.Limit = &v
}

// GetRemaining returns the Remaining field value if set, zero value otherwise.
func (o *AccountStatusResponseRateLimit) GetRemaining() int32 {
	if o == nil || IsNil(o.Remaining) {
		var ret int32
		return ret
	}
	return *o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountStatusResponseRateLimit) GetRemainingOk() (*int32, bool) {
	if o == nil || IsNil(o.Remaining) {
		return nil, false
	}
	return o.Remaining, true
}

// HasRemaining returns a boolean if a field has been set.
func (o *AccountStatusResponseRateLimit) HasRemaining() bool {
	if o != nil && !IsNil(o.Remaining) {
		return true
	}

	return false
}

// SetRemaining gets a reference to the given int32 and assigns it to the Remaining field.
func (o *AccountStatusResponseRateLimit) SetRemaining(v int32) {
	o.Remaining = &v
}

// GetReset returns the Reset field value if set, zero value otherwise.
func (o *AccountStatusResponseRateLimit) GetReset() int32 {
	if o == nil || IsNil(o.Reset) {
		var ret int32
		return ret
	}
	return *o.Reset
}

// GetResetOk returns a tuple with the Reset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountStatusResponseRateLimit) GetResetOk() (*int32, bool) {
	if o == nil || IsNil(o.Reset) {
		return nil, false
	}
	return o.Reset, true
}

// HasReset returns a boolean if a field has been set.
func (o *AccountStatusResponseRateLimit) HasReset() bool {
	if o != nil && !IsNil(o.Reset) {
		return true
	}

	return false
}

// SetReset gets a reference to the given int32 and assigns it to the Reset field.
func (o *AccountStatusResponseRateLimit) SetReset(v int32) {
	o.Reset = &v
}

func (o AccountStatusResponseRateLimit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountStatusResponseRateLimit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Remaining) {
		toSerialize["remaining"] = o.Remaining
	}
	if !IsNil(o.Reset) {
		toSerialize["reset"] = o.Reset
	}
	return toSerialize, nil
}

type NullableAccountStatusResponseRateLimit struct {
	value *AccountStatusResponseRateLimit
	isSet bool
}

func (v NullableAccountStatusResponseRateLimit) Get() *AccountStatusResponseRateLimit {
	return v.value
}

func (v *NullableAccountStatusResponseRateLimit) Set(val *AccountStatusResponseRateLimit) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountStatusResponseRateLimit) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountStatusResponseRateLimit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountStatusResponseRateLimit(val *AccountStatusResponseRateLimit) *NullableAccountStatusResponseRateLimit {
	return &NullableAccountStatusResponseRateLimit{value: val, isSet: true}
}

func (v NullableAccountStatusResponseRateLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountStatusResponseRateLimit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


