/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyDecisionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyDecisionResponse{}

// VerifyDecisionResponse struct for VerifyDecisionResponse
type VerifyDecisionResponse struct {
	// Recommended action. Policy authority stays with the caller.
	Recommendation string `json:"recommendation"`
	// Signals that drove the recommendation. Values correspond to VerifyReason identifiers.
	Reasons []string `json:"reasons"`
}

type _VerifyDecisionResponse VerifyDecisionResponse

// NewVerifyDecisionResponse instantiates a new VerifyDecisionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyDecisionResponse(recommendation string, reasons []string) *VerifyDecisionResponse {
	this := VerifyDecisionResponse{}
	this.Recommendation = recommendation
	this.Reasons = reasons
	return &this
}

// NewVerifyDecisionResponseWithDefaults instantiates a new VerifyDecisionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyDecisionResponseWithDefaults() *VerifyDecisionResponse {
	this := VerifyDecisionResponse{}
	return &this
}

// GetRecommendation returns the Recommendation field value
func (o *VerifyDecisionResponse) GetRecommendation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recommendation
}

// GetRecommendationOk returns a tuple with the Recommendation field value
// and a boolean to check if the value has been set.
func (o *VerifyDecisionResponse) GetRecommendationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recommendation, true
}

// SetRecommendation sets field value
func (o *VerifyDecisionResponse) SetRecommendation(v string) {
	o.Recommendation = v
}

// GetReasons returns the Reasons field value
func (o *VerifyDecisionResponse) GetReasons() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value
// and a boolean to check if the value has been set.
func (o *VerifyDecisionResponse) GetReasonsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reasons, true
}

// SetReasons sets field value
func (o *VerifyDecisionResponse) SetReasons(v []string) {
	o.Reasons = v
}

func (o VerifyDecisionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyDecisionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recommendation"] = o.Recommendation
	toSerialize["reasons"] = o.Reasons
	return toSerialize, nil
}

func (o *VerifyDecisionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recommendation",
		"reasons",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyDecisionResponse := _VerifyDecisionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyDecisionResponse)

	if err != nil {
		return err
	}

	*o = VerifyDecisionResponse(varVerifyDecisionResponse)

	return err
}

type NullableVerifyDecisionResponse struct {
	value *VerifyDecisionResponse
	isSet bool
}

func (v NullableVerifyDecisionResponse) Get() *VerifyDecisionResponse {
	return v.value
}

func (v *NullableVerifyDecisionResponse) Set(val *VerifyDecisionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyDecisionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyDecisionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyDecisionResponse(val *VerifyDecisionResponse) *NullableVerifyDecisionResponse {
	return &NullableVerifyDecisionResponse{value: val, isSet: true}
}

func (v NullableVerifyDecisionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyDecisionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


