/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyDomainResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyDomainResponse{}

// VerifyDomainResponse struct for VerifyDomainResponse
type VerifyDomainResponse struct {
	// The domain behind the address.
	Name string `json:"name"`
	// Host classification. A domain can carry more than one type.
	Types []string `json:"types,omitempty"`
	// 0-100 domain reputation score, higher is better. Null when the domain has not been scored yet.
	Score NullableFloat32 `json:"score,omitempty"`
	// An SPF record exists.
	Spf NullableBool `json:"spf,omitempty"`
	// A DKIM record was found.
	Dkim NullableBool `json:"dkim,omitempty"`
	// A DMARC record exists.
	Dmarc NullableBool `json:"dmarc,omitempty"`
	// The published DMARC policy.
	DmarcPolicy NullableString `json:"dmarc_policy,omitempty"`
	// An MTA-STS policy is published.
	MtaSts NullableBool `json:"mta_sts,omitempty"`
	// A TLS-RPT record exists.
	TlsRpt NullableBool `json:"tls_rpt,omitempty"`
	// A BIMI record exists.
	Bimi NullableBool `json:"bimi,omitempty"`
	// DANE/TLSA records exist for the MX hosts.
	Dane NullableBool `json:"dane,omitempty"`
	// Number of public DNS blacklists currently listing this domain's mail infrastructure.
	Blacklists NullableInt32 `json:"blacklists,omitempty"`
	// DNSSEC chain status.
	Dnssec NullableString `json:"dnssec,omitempty"`
	// A CAA record restricts which CAs may issue certificates.
	Caa NullableBool `json:"caa,omitempty"`
}

type _VerifyDomainResponse VerifyDomainResponse

// NewVerifyDomainResponse instantiates a new VerifyDomainResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyDomainResponse(name string) *VerifyDomainResponse {
	this := VerifyDomainResponse{}
	this.Name = name
	return &this
}

// NewVerifyDomainResponseWithDefaults instantiates a new VerifyDomainResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyDomainResponseWithDefaults() *VerifyDomainResponse {
	this := VerifyDomainResponse{}
	return &this
}

// GetName returns the Name field value
func (o *VerifyDomainResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VerifyDomainResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VerifyDomainResponse) SetName(v string) {
	o.Name = v
}

// GetTypes returns the Types field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Types
}

// GetTypesOk returns a tuple with the Types field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.Types) {
		return nil, false
	}
	return o.Types, true
}

// HasTypes returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasTypes() bool {
	if o != nil && !IsNil(o.Types) {
		return true
	}

	return false
}

// SetTypes gets a reference to the given []string and assigns it to the Types field.
func (o *VerifyDomainResponse) SetTypes(v []string) {
	o.Types = v
}

// GetScore returns the Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetScore() float32 {
	if o == nil || IsNil(o.Score.Get()) {
		var ret float32
		return ret
	}
	return *o.Score.Get()
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Score.Get(), o.Score.IsSet()
}

// HasScore returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasScore() bool {
	if o != nil && o.Score.IsSet() {
		return true
	}

	return false
}

// SetScore gets a reference to the given NullableFloat32 and assigns it to the Score field.
func (o *VerifyDomainResponse) SetScore(v float32) {
	o.Score.Set(&v)
}
// SetScoreNil sets the value for Score to be an explicit nil
func (o *VerifyDomainResponse) SetScoreNil() {
	o.Score.Set(nil)
}

// UnsetScore ensures that no value is present for Score, not even an explicit nil
func (o *VerifyDomainResponse) UnsetScore() {
	o.Score.Unset()
}

// GetSpf returns the Spf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetSpf() bool {
	if o == nil || IsNil(o.Spf.Get()) {
		var ret bool
		return ret
	}
	return *o.Spf.Get()
}

// GetSpfOk returns a tuple with the Spf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetSpfOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Spf.Get(), o.Spf.IsSet()
}

// HasSpf returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasSpf() bool {
	if o != nil && o.Spf.IsSet() {
		return true
	}

	return false
}

// SetSpf gets a reference to the given NullableBool and assigns it to the Spf field.
func (o *VerifyDomainResponse) SetSpf(v bool) {
	o.Spf.Set(&v)
}
// SetSpfNil sets the value for Spf to be an explicit nil
func (o *VerifyDomainResponse) SetSpfNil() {
	o.Spf.Set(nil)
}

// UnsetSpf ensures that no value is present for Spf, not even an explicit nil
func (o *VerifyDomainResponse) UnsetSpf() {
	o.Spf.Unset()
}

// GetDkim returns the Dkim field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetDkim() bool {
	if o == nil || IsNil(o.Dkim.Get()) {
		var ret bool
		return ret
	}
	return *o.Dkim.Get()
}

// GetDkimOk returns a tuple with the Dkim field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetDkimOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dkim.Get(), o.Dkim.IsSet()
}

// HasDkim returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasDkim() bool {
	if o != nil && o.Dkim.IsSet() {
		return true
	}

	return false
}

// SetDkim gets a reference to the given NullableBool and assigns it to the Dkim field.
func (o *VerifyDomainResponse) SetDkim(v bool) {
	o.Dkim.Set(&v)
}
// SetDkimNil sets the value for Dkim to be an explicit nil
func (o *VerifyDomainResponse) SetDkimNil() {
	o.Dkim.Set(nil)
}

// UnsetDkim ensures that no value is present for Dkim, not even an explicit nil
func (o *VerifyDomainResponse) UnsetDkim() {
	o.Dkim.Unset()
}

// GetDmarc returns the Dmarc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetDmarc() bool {
	if o == nil || IsNil(o.Dmarc.Get()) {
		var ret bool
		return ret
	}
	return *o.Dmarc.Get()
}

// GetDmarcOk returns a tuple with the Dmarc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetDmarcOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dmarc.Get(), o.Dmarc.IsSet()
}

// HasDmarc returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasDmarc() bool {
	if o != nil && o.Dmarc.IsSet() {
		return true
	}

	return false
}

// SetDmarc gets a reference to the given NullableBool and assigns it to the Dmarc field.
func (o *VerifyDomainResponse) SetDmarc(v bool) {
	o.Dmarc.Set(&v)
}
// SetDmarcNil sets the value for Dmarc to be an explicit nil
func (o *VerifyDomainResponse) SetDmarcNil() {
	o.Dmarc.Set(nil)
}

// UnsetDmarc ensures that no value is present for Dmarc, not even an explicit nil
func (o *VerifyDomainResponse) UnsetDmarc() {
	o.Dmarc.Unset()
}

// GetDmarcPolicy returns the DmarcPolicy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetDmarcPolicy() string {
	if o == nil || IsNil(o.DmarcPolicy.Get()) {
		var ret string
		return ret
	}
	return *o.DmarcPolicy.Get()
}

// GetDmarcPolicyOk returns a tuple with the DmarcPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetDmarcPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DmarcPolicy.Get(), o.DmarcPolicy.IsSet()
}

// HasDmarcPolicy returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasDmarcPolicy() bool {
	if o != nil && o.DmarcPolicy.IsSet() {
		return true
	}

	return false
}

// SetDmarcPolicy gets a reference to the given NullableString and assigns it to the DmarcPolicy field.
func (o *VerifyDomainResponse) SetDmarcPolicy(v string) {
	o.DmarcPolicy.Set(&v)
}
// SetDmarcPolicyNil sets the value for DmarcPolicy to be an explicit nil
func (o *VerifyDomainResponse) SetDmarcPolicyNil() {
	o.DmarcPolicy.Set(nil)
}

// UnsetDmarcPolicy ensures that no value is present for DmarcPolicy, not even an explicit nil
func (o *VerifyDomainResponse) UnsetDmarcPolicy() {
	o.DmarcPolicy.Unset()
}

// GetMtaSts returns the MtaSts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetMtaSts() bool {
	if o == nil || IsNil(o.MtaSts.Get()) {
		var ret bool
		return ret
	}
	return *o.MtaSts.Get()
}

// GetMtaStsOk returns a tuple with the MtaSts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetMtaStsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.MtaSts.Get(), o.MtaSts.IsSet()
}

// HasMtaSts returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasMtaSts() bool {
	if o != nil && o.MtaSts.IsSet() {
		return true
	}

	return false
}

// SetMtaSts gets a reference to the given NullableBool and assigns it to the MtaSts field.
func (o *VerifyDomainResponse) SetMtaSts(v bool) {
	o.MtaSts.Set(&v)
}
// SetMtaStsNil sets the value for MtaSts to be an explicit nil
func (o *VerifyDomainResponse) SetMtaStsNil() {
	o.MtaSts.Set(nil)
}

// UnsetMtaSts ensures that no value is present for MtaSts, not even an explicit nil
func (o *VerifyDomainResponse) UnsetMtaSts() {
	o.MtaSts.Unset()
}

// GetTlsRpt returns the TlsRpt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetTlsRpt() bool {
	if o == nil || IsNil(o.TlsRpt.Get()) {
		var ret bool
		return ret
	}
	return *o.TlsRpt.Get()
}

// GetTlsRptOk returns a tuple with the TlsRpt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetTlsRptOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.TlsRpt.Get(), o.TlsRpt.IsSet()
}

// HasTlsRpt returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasTlsRpt() bool {
	if o != nil && o.TlsRpt.IsSet() {
		return true
	}

	return false
}

// SetTlsRpt gets a reference to the given NullableBool and assigns it to the TlsRpt field.
func (o *VerifyDomainResponse) SetTlsRpt(v bool) {
	o.TlsRpt.Set(&v)
}
// SetTlsRptNil sets the value for TlsRpt to be an explicit nil
func (o *VerifyDomainResponse) SetTlsRptNil() {
	o.TlsRpt.Set(nil)
}

// UnsetTlsRpt ensures that no value is present for TlsRpt, not even an explicit nil
func (o *VerifyDomainResponse) UnsetTlsRpt() {
	o.TlsRpt.Unset()
}

// GetBimi returns the Bimi field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetBimi() bool {
	if o == nil || IsNil(o.Bimi.Get()) {
		var ret bool
		return ret
	}
	return *o.Bimi.Get()
}

// GetBimiOk returns a tuple with the Bimi field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetBimiOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bimi.Get(), o.Bimi.IsSet()
}

// HasBimi returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasBimi() bool {
	if o != nil && o.Bimi.IsSet() {
		return true
	}

	return false
}

// SetBimi gets a reference to the given NullableBool and assigns it to the Bimi field.
func (o *VerifyDomainResponse) SetBimi(v bool) {
	o.Bimi.Set(&v)
}
// SetBimiNil sets the value for Bimi to be an explicit nil
func (o *VerifyDomainResponse) SetBimiNil() {
	o.Bimi.Set(nil)
}

// UnsetBimi ensures that no value is present for Bimi, not even an explicit nil
func (o *VerifyDomainResponse) UnsetBimi() {
	o.Bimi.Unset()
}

// GetDane returns the Dane field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetDane() bool {
	if o == nil || IsNil(o.Dane.Get()) {
		var ret bool
		return ret
	}
	return *o.Dane.Get()
}

// GetDaneOk returns a tuple with the Dane field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetDaneOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dane.Get(), o.Dane.IsSet()
}

// HasDane returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasDane() bool {
	if o != nil && o.Dane.IsSet() {
		return true
	}

	return false
}

// SetDane gets a reference to the given NullableBool and assigns it to the Dane field.
func (o *VerifyDomainResponse) SetDane(v bool) {
	o.Dane.Set(&v)
}
// SetDaneNil sets the value for Dane to be an explicit nil
func (o *VerifyDomainResponse) SetDaneNil() {
	o.Dane.Set(nil)
}

// UnsetDane ensures that no value is present for Dane, not even an explicit nil
func (o *VerifyDomainResponse) UnsetDane() {
	o.Dane.Unset()
}

// GetBlacklists returns the Blacklists field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetBlacklists() int32 {
	if o == nil || IsNil(o.Blacklists.Get()) {
		var ret int32
		return ret
	}
	return *o.Blacklists.Get()
}

// GetBlacklistsOk returns a tuple with the Blacklists field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetBlacklistsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Blacklists.Get(), o.Blacklists.IsSet()
}

// HasBlacklists returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasBlacklists() bool {
	if o != nil && o.Blacklists.IsSet() {
		return true
	}

	return false
}

// SetBlacklists gets a reference to the given NullableInt32 and assigns it to the Blacklists field.
func (o *VerifyDomainResponse) SetBlacklists(v int32) {
	o.Blacklists.Set(&v)
}
// SetBlacklistsNil sets the value for Blacklists to be an explicit nil
func (o *VerifyDomainResponse) SetBlacklistsNil() {
	o.Blacklists.Set(nil)
}

// UnsetBlacklists ensures that no value is present for Blacklists, not even an explicit nil
func (o *VerifyDomainResponse) UnsetBlacklists() {
	o.Blacklists.Unset()
}

// GetDnssec returns the Dnssec field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetDnssec() string {
	if o == nil || IsNil(o.Dnssec.Get()) {
		var ret string
		return ret
	}
	return *o.Dnssec.Get()
}

// GetDnssecOk returns a tuple with the Dnssec field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetDnssecOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dnssec.Get(), o.Dnssec.IsSet()
}

// HasDnssec returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasDnssec() bool {
	if o != nil && o.Dnssec.IsSet() {
		return true
	}

	return false
}

// SetDnssec gets a reference to the given NullableString and assigns it to the Dnssec field.
func (o *VerifyDomainResponse) SetDnssec(v string) {
	o.Dnssec.Set(&v)
}
// SetDnssecNil sets the value for Dnssec to be an explicit nil
func (o *VerifyDomainResponse) SetDnssecNil() {
	o.Dnssec.Set(nil)
}

// UnsetDnssec ensures that no value is present for Dnssec, not even an explicit nil
func (o *VerifyDomainResponse) UnsetDnssec() {
	o.Dnssec.Unset()
}

// GetCaa returns the Caa field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyDomainResponse) GetCaa() bool {
	if o == nil || IsNil(o.Caa.Get()) {
		var ret bool
		return ret
	}
	return *o.Caa.Get()
}

// GetCaaOk returns a tuple with the Caa field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyDomainResponse) GetCaaOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Caa.Get(), o.Caa.IsSet()
}

// HasCaa returns a boolean if a field has been set.
func (o *VerifyDomainResponse) HasCaa() bool {
	if o != nil && o.Caa.IsSet() {
		return true
	}

	return false
}

// SetCaa gets a reference to the given NullableBool and assigns it to the Caa field.
func (o *VerifyDomainResponse) SetCaa(v bool) {
	o.Caa.Set(&v)
}
// SetCaaNil sets the value for Caa to be an explicit nil
func (o *VerifyDomainResponse) SetCaaNil() {
	o.Caa.Set(nil)
}

// UnsetCaa ensures that no value is present for Caa, not even an explicit nil
func (o *VerifyDomainResponse) UnsetCaa() {
	o.Caa.Unset()
}

func (o VerifyDomainResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyDomainResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Types != nil {
		toSerialize["types"] = o.Types
	}
	if o.Score.IsSet() {
		toSerialize["score"] = o.Score.Get()
	}
	if o.Spf.IsSet() {
		toSerialize["spf"] = o.Spf.Get()
	}
	if o.Dkim.IsSet() {
		toSerialize["dkim"] = o.Dkim.Get()
	}
	if o.Dmarc.IsSet() {
		toSerialize["dmarc"] = o.Dmarc.Get()
	}
	if o.DmarcPolicy.IsSet() {
		toSerialize["dmarc_policy"] = o.DmarcPolicy.Get()
	}
	if o.MtaSts.IsSet() {
		toSerialize["mta_sts"] = o.MtaSts.Get()
	}
	if o.TlsRpt.IsSet() {
		toSerialize["tls_rpt"] = o.TlsRpt.Get()
	}
	if o.Bimi.IsSet() {
		toSerialize["bimi"] = o.Bimi.Get()
	}
	if o.Dane.IsSet() {
		toSerialize["dane"] = o.Dane.Get()
	}
	if o.Blacklists.IsSet() {
		toSerialize["blacklists"] = o.Blacklists.Get()
	}
	if o.Dnssec.IsSet() {
		toSerialize["dnssec"] = o.Dnssec.Get()
	}
	if o.Caa.IsSet() {
		toSerialize["caa"] = o.Caa.Get()
	}
	return toSerialize, nil
}

func (o *VerifyDomainResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyDomainResponse := _VerifyDomainResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyDomainResponse)

	if err != nil {
		return err
	}

	*o = VerifyDomainResponse(varVerifyDomainResponse)

	return err
}

type NullableVerifyDomainResponse struct {
	value *VerifyDomainResponse
	isSet bool
}

func (v NullableVerifyDomainResponse) Get() *VerifyDomainResponse {
	return v.value
}

func (v *NullableVerifyDomainResponse) Set(val *VerifyDomainResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyDomainResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyDomainResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyDomainResponse(val *VerifyDomainResponse) *NullableVerifyDomainResponse {
	return &NullableVerifyDomainResponse{value: val, isSet: true}
}

func (v NullableVerifyDomainResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyDomainResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


