/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
)

// checks if the VerifyJobResponseProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyJobResponseProgress{}

// VerifyJobResponseProgress Processing progress.
type VerifyJobResponseProgress struct {
	Total *int32 `json:"total,omitempty"`
	Done *int32 `json:"done,omitempty"`
}

// NewVerifyJobResponseProgress instantiates a new VerifyJobResponseProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyJobResponseProgress() *VerifyJobResponseProgress {
	this := VerifyJobResponseProgress{}
	return &this
}

// NewVerifyJobResponseProgressWithDefaults instantiates a new VerifyJobResponseProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyJobResponseProgressWithDefaults() *VerifyJobResponseProgress {
	this := VerifyJobResponseProgress{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *VerifyJobResponseProgress) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyJobResponseProgress) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *VerifyJobResponseProgress) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *VerifyJobResponseProgress) SetTotal(v int32) {
	o.Total = &v
}

// GetDone returns the Done field value if set, zero value otherwise.
func (o *VerifyJobResponseProgress) GetDone() int32 {
	if o == nil || IsNil(o.Done) {
		var ret int32
		return ret
	}
	return *o.Done
}

// GetDoneOk returns a tuple with the Done field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyJobResponseProgress) GetDoneOk() (*int32, bool) {
	if o == nil || IsNil(o.Done) {
		return nil, false
	}
	return o.Done, true
}

// HasDone returns a boolean if a field has been set.
func (o *VerifyJobResponseProgress) HasDone() bool {
	if o != nil && !IsNil(o.Done) {
		return true
	}

	return false
}

// SetDone gets a reference to the given int32 and assigns it to the Done field.
func (o *VerifyJobResponseProgress) SetDone(v int32) {
	o.Done = &v
}

func (o VerifyJobResponseProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyJobResponseProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Done) {
		toSerialize["done"] = o.Done
	}
	return toSerialize, nil
}

type NullableVerifyJobResponseProgress struct {
	value *VerifyJobResponseProgress
	isSet bool
}

func (v NullableVerifyJobResponseProgress) Get() *VerifyJobResponseProgress {
	return v.value
}

func (v *NullableVerifyJobResponseProgress) Set(val *VerifyJobResponseProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyJobResponseProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyJobResponseProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyJobResponseProgress(val *VerifyJobResponseProgress) *NullableVerifyJobResponseProgress {
	return &NullableVerifyJobResponseProgress{value: val, isSet: true}
}

func (v NullableVerifyJobResponseProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyJobResponseProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


