/*
EmailSherlock API

Verify one email address or a batch over HTTPS with an API key. Authenticate with the X-API-Key header. Billing is user-level credits; each call returns the remaining balance in the X-Credits-Remaining header.  Sandbox: a key that starts with es_test_ runs in sandbox mode. It returns deterministic fixtured data on the same endpoints and response shape, never spends credits, and marks every response with X-Sandbox: true. The local part drives the verdict so you can test each branch: valid@, invalid@, catch-all@, disposable@, role@, unknown@ and pending@ pin a result (pending@ yields reason verification_pending, the deferred-batch outcome to retry later); ratelimit@ returns 429 and servererror@ returns 503 so you can exercise error handling. On the async jobs endpoint (POST /v1/verify/jobs), put async@ or slowjob@ in the batch and the sandbox reproduces the real submit-poll-complete lifecycle: the submit returns processing and the job completes after a few seconds, so you can build and test your polling loop before going live; without it, sandbox jobs complete immediately. Any other address maps to a stable result. Live keys start with es_live_. Full reference at https://emailsherlock.com/api/docs

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package genclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyJobRequest{}

// VerifyJobRequest struct for VerifyJobRequest
type VerifyJobRequest struct {
	// The addresses to verify. Non-empty, capped at the job limit (10000).
	Emails []string `json:"emails"`
}

type _VerifyJobRequest VerifyJobRequest

// NewVerifyJobRequest instantiates a new VerifyJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyJobRequest(emails []string) *VerifyJobRequest {
	this := VerifyJobRequest{}
	this.Emails = emails
	return &this
}

// NewVerifyJobRequestWithDefaults instantiates a new VerifyJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyJobRequestWithDefaults() *VerifyJobRequest {
	this := VerifyJobRequest{}
	return &this
}

// GetEmails returns the Emails field value
func (o *VerifyJobRequest) GetEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *VerifyJobRequest) GetEmailsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *VerifyJobRequest) SetEmails(v []string) {
	o.Emails = v
}

func (o VerifyJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emails"] = o.Emails
	return toSerialize, nil
}

func (o *VerifyJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyJobRequest := _VerifyJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyJobRequest)

	if err != nil {
		return err
	}

	*o = VerifyJobRequest(varVerifyJobRequest)

	return err
}

type NullableVerifyJobRequest struct {
	value *VerifyJobRequest
	isSet bool
}

func (v NullableVerifyJobRequest) Get() *VerifyJobRequest {
	return v.value
}

func (v *NullableVerifyJobRequest) Set(val *VerifyJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyJobRequest(val *VerifyJobRequest) *NullableVerifyJobRequest {
	return &NullableVerifyJobRequest{value: val, isSet: true}
}

func (v NullableVerifyJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


